= LibreOffice error codes
Since various people have reported issues using unoconv related to LibreOffice,
it's clear we need to list the various errors and give some explanation.

If you have more information to improve this document, let me know !

== How to decipher LibreOffice error codes
Unfortunately the LibreOffice error codes is a combination of project area,
error class and error code. The combination of these three provides some
indication of what the cause is, although in most cases this is not conclusive.

The authoritative source for ErrCodes are the following files:

List of ErrCode classifications::
 - http://docs.libreoffice.org/tools/html/errcode_8hxx_source.html

List of other related ErrCode classifications::
 - http://docs.libreoffice.org/svtools/html/sfxecode_8hxx.html
 - http://docs.libreoffice.org/svtools/html/soerr_8hxx.html

----
01234567012345670123456701234567
||   ||          |||   ||      |
Warning           ||   ||      |
 |   ||           ||   ||      |
 Dynamic          ||   ||      |
      |           ||   ||      |
      Subsystemarea|   ||      |
                   |   ||      |
                   |   ||      |
                   |   ||      |
                   Class|      |
                        |      |
                        |      |
                        |      |
                        Code
----


== UnoException ErrCode

=== 283
Binary: 000:00001:00011011

    Area: 0 (ERRCODE_AREA_TOOLS)
    Class: 1 (ERRCODE_CLASS_ABORT)
    Code: 27 (ERRCODE_IO_ABORT)

=== 1287
Binary: 000:00101:00000111

    Area: 0 (ERRCODE_AREA_TOOLS)
    Class: 5 (ERRCODE_CLASS_ACCESS)
    Code: 7 (ERRCODE_IO_ACCESSDENIED)

=== 2074
Binary: 000:01000:00011010

    Area: 0 (ERRCODE_AREA_TOOLS)
    Class: 8 (ERRCODE_CLASS_PARAMETER)
    Code: 26 (ERRCODE_IO_INVALIDPARAMETER)

=== 3088
Binary: 000:01100:00010000

    Area: 0 (ERRCODE_AREA_TOOLS)
    Class: 12 (ERRCODE_CLASS_WRITE)
    Code: 16 (ERRCODE_IO_CANTWRITE)

=== 19468 -- ERRCODE_SFX_DOCUMENTREADONLY
Binary: 010:01100:00001100

    Area: 2 (ERRCODE_AREA_SFX)
    Class: 12 (ERRCODE_CLASS_WRITE)
    Code: 12 (ERRCODE_IO_NOTSUPPORTED)
