= Import and export filters

== Import filter options
See also:

 * http://wiki.services.openoffice.org/wiki/Documentation/DevGuide/Spreadsheets/Filter_Options[Spreadsheet filter options]

== Generic export filter options

[width="100%",cols="5,^2,^2,10",options="header"]
|==========================================================
|Option name               |Type   |Default |Description
|Size                      |       |        |
|==========================================================


== PDF export filter options
See also:

 * http://wiki.services.openoffice.org/wiki/API/Tutorials/PDF_export[API/Tutorials/PDF export]
 * http://specs.openoffice.org/appwide/pdf_export/PDFExportDialog.odt[PDF Export Dialog Specification]

[width="100%",cols="5,^2,^2,10",options="header"]
|==========================================================
|Option name               |Type   |Default |Description
|AllowDuplicateFieldNames  |boolean|False   |Specifies whether multiple form fields exported
are allowed to have the same field name. Since: OOo 3.3 [DEV300_m65] (See
http://www.openoffice.org/issues/show_bug.cgi?id=103932[i103932])
|CenterWindow              |boolean|False   |Specifies that the PDF viewer
window is centered to the screen when the PDF document is opened.
|Changes                   |integer|4       |
*0*:Not permitted
*1*:Inserting, deleting and rotating pages
*2*:Filling in form fields
*3*:Commenting, filling in form fields
*4*:Any except extracting pages
|ConvertOOoTargetToPDFTarget|boolean|False   |Specifies that the target
documents with .od[tpgs] extension, will have that extension changed to .pdf
when the link is exported to PDF. The source document remains untouched.
|DisplayPDFDocumentTitle   |boolean|True    |Specifies that the title of the
document, if present in the document properties, is displayed in the PDF
viewer window title bar.
|DocumentOpenPassword      |string |        |This is the password that allows
the user to open the PDF file is "EncryptFile" is set to true.
|EnableCopyingOfContent    |boolean|True    |Specifies that the pages and the
document content can be extracted to be used in other documents (copy and
paste).
|EnableTextAccessForAccessibilityTools|boolean|True    |Specifies that the
document content can be extracted to be used in accessibility applications.
|EncryptFile               |boolean|False   |If true, selects to encrypt the
PDF document with a password. The PDF file can be opened only when the user
enters the correct password.
|ExportBookmarks           |boolean|True    |Specifies if bookmarks are
exported to PDF.
|ExportBookmarksToPDFDestination|boolean|False   |Specifies that the bookmarks
contained in the source OpenOffice.org file should be exported to the PDF file
as Named Destination (see PDF 1.4 section 8.2.1).
|ExportFormFields          |boolean|True    |Specifies whether form fields are
exported as widgets or only their fixed print representation is exported.
|ExportLinksRelativeFsys   |boolean|False   |Specifies that the file system
related hyperlinks (file:// method) present in the document will be exported
as relative to the source document location.
|ExportNotes               |boolean|False   |Specifies if notes are exported
to PDF.
|ExportNotesPages          |boolean|False   |Specifies if notes pages are
exported to PDF. (Notes pages are available in Impress documents only).
|FirstPageOnLeft           |boolean|False   |Used with the value 3 of the
PageLayout property when the first page (odd) should be on the left side of
the screen.
|FormsType                 |integer|0       |Specifies the submitted format of
a PDF form.
*0*:FDF format
*1*:PDF format
*2*:HTML format
*3*:XML format
|HideViewerMenubar         |boolean|False   |Specifies whether to hide the PDF
viewer menubar when the document is active.
|HideViewerToolbar         |boolean|False   |Specifies whether to hide the PDF
viewer toolbar when the document is active.
|hideViewerWindowControls  |boolean|False   |Specifies whether to hide the PDF
viewer controls when the document is active.
|InitialPage               |integer|1       |Specifies the page on which a PDF
document should be opened in the viewer application.
|InitialView               |integer|0       |Specifies how the PDF document
should be displayed when opened. *0*:meaning neither outlines or thumbnails,
*1*:meaning the document is opened with outline pane opened, *2*:meaning the
document is opened with thumbnail pane opened
|IsAddStream               |boolean|False   |Specifies that a stream is inserted
to the PDF file which contains the original document for archiving purposes.
This option is active only if the PDF Import extension is installed. 
|IsSkipEmptyPages          |boolean|False   |Specifies that automatically
inserted empty pages are suppressed. This option is active only if storing
Writer documents.
|Magnification             |integer|0       |Specifies the action to be
performed when the PDF document is opened
*0*:meaning opens with default zoom magnification
*1*:meaning opens magnified to fit the entire page within the window
*2*:meaning opens magnified to fit the entire page width within the window
*3*:meaning opens magnified to fit the entire width of its boundig box within
the window (cuts out margins) *4*:means with a zoom level given in the “Zoom”
property.
|MaxImageResolution        |integer|300     |If the property
If the property ReduceImageResolution is set to true all images will be reduced
to the given value in DPI. Possible values: *75*, *150*, *300*, *600*, *1200*
|OpenBookmarkLevels        |integer|-1      |Specifies how many bookmark
levels should be opened in the reader application when the PDF gets opened. -1
means all levels, non-negative numbers mean the respective number of levels.
|OpenInFullScreenMode      |boolean|False   |Specifies that the PDF viewer
window is opened full screen, on top of all windows.
|PageLayout                |integer|0       |Specifies the page layout to be
used when the document is opened.
*0*:meaning display the pages according to the reader configuration
*1*:meaning display one page at a time
*2*:meaning display the pages in one column
*3*:meaning display the pages in two columns odd pages on the right, to have
the odd pages on the left the FirstPageOnLeft properties should be used as well.
|PageRange                 |string |        |If this property is set, it
indicates the range of pages to be printed. If you want to print all the pages,
leave this property unset. If you want to export a selection, leave this
property unset, setting only the property Selection. 
|PDFViewSelection          |integer|0       |Specifies the way the exported
PDF will be viewed (experienced) by the user.
*0*:specifies that the PDF will be exported with all the links external to the
document treated as URI.
*1*:specifies that the PDF will be exported in order to be viewed through a PDF
reader application only. Valid only if not exporting to PDF/A-1
(e.g. SelectPdfVersion not set to 1).
*2*:specifies that the PDF will be exported in order to be viewed through an
Internet browser, using the PDF plug-in provided with it. The bookmark of the
URI will be rendered compatible with the target bookmark generated with OOo
PDF Export feature (see ExportBookmarksToPDFDestination property). 
|PermissionPassword        |string |        |This is the password that allows
the user to access some permissions restricted if "RestrictPermissions" is set
to true.
|Printing                  |integer|2       |
*0*:Not permitted
*1*:Low resolution only(150 DPI)
*2*:Maximum Resolution allowed
|Quality                   |integer|90      |Specifies quality of the JPG
export. A higher value results in higher quality and file size. Specifies
quality of the JPG export. A higher value results in higher quality and file.
*1*:represents lowest value that can be used. The lower the value, the less
good is the compression quality and the bigger is be the file size
*100*:represents highest value that can be used. The higher the value, the
better is the compression quality and the smaller is the file size. (1 - 100)
|ReduceImageResolution     |boolean|False   |Specifies if the resolution of
each image is reduced to the resolution specified by the property
MaxImageResolution.
|ResizeWindowToInitialPage |boolean|False   |Specifies that the PDF viewer
window is opened full screen when the document is opened.
|RestrictPermissionPassword|boolean|False   |If true, selects to restrict some
permissions. The permissions can be changed only when the user enters the
correct password.
|Selection                 |any?   |        |An any corresponding to the
current selection in the document.
|SelectPdfVersion          |integer|0       |Specifies the PDF version to emit.
*0*:PDF 1.4
*1*:PDF/A-1 (ISO 19005-1:2005)
|UseLosslessCompression    |boolean|False   |Specifies if graphics are exported
to PDF using a lossless compression eg. PNG or if they are compressed using the
JPEG format.
|UseTaggedPDF              |boolean|False   |Determines if PDF are created by
using special tags also known as Tagged PDF.
|UseTransitionEffects      |boolean|False   |Specifies slide transitions are
exported to PDF. This option is active only if storing Impress documents.
|Watermark                 |string |        |Specifies the text for a
watermark to be drawn on every page of the exported PDF file.
|Zoom                      |integer|100     |Specifies the zoom level a PDF
document is opened with. Only valid if "Magnification" is set to "4".
|===========================================================

